#按照设备品类、调和类型、设备名称 这3个参数
-
  - "灯泡"
  - "冷暖白光灯"
  - CW
-
  - "灯泡"
  - "5路彩灯"
  - RGBCW
-
  - "灯泡"
  - "5路彩灯(支持音乐律动)"
  - RGBCWRhythm
-
  - "灯泡"
  - "4路彩灯(支持音乐律动)"
  - RGBWRhythm
-
  - "风扇灯"
  - "单色风扇灯"
  - Fan
-
  - "风扇灯"
  - "双色风扇灯"
  - Fan_CW
-
  - "落地扇"
  - "落地扇"
  - Fans
-
  - "磁吸灯"
  - "冷暖磁吸灯"
  - Magn_CW
-
  - "吸顶灯"
  - "冷暖吸顶灯"
  - Ceiling_CW
-
  - "灯带"
  - "五路彩光灯带(支持音乐律动)"
  - 5_Belt_Rhym
-
  - "灯带"
  - "单色灯带"
  - 1_Belt
-
  - "灯带"
  - "冷暖白光灯带"
  - 2_Belt
-
  - "灯带"
  - "RGB彩光灯带"
  - 3_Belt
-
  - "灯带"
  - "四路彩光灯带"
  - 4_Belt
-
  - "灯带"
  - "五路彩光灯带"
  - 5_Belt
-
  - "开关"
  - "一路开关"
  - Switch